# Generated by Django 3.2.13 on 2022-06-10 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('idOrganization', models.CharField(max_length=32)),
                ('boardUrl', models.URLField(blank=True, null=True)),
                ('shortLink', models.CharField(max_length=10, unique=True)),
                ('shortUrl', models.URLField(unique=True)),
                ('dateLastActivity', models.DateTimeField(blank=True, null=True)),
                ('dateLastView', models.DateTimeField(blank=True, null=True)),
                ('ixUpdate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('activityBlocked', models.BooleanField(default=False)),
                ('avatarHash', models.CharField(blank=True, max_length=32, null=True)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('nonPublicAvailable', models.BooleanField(blank=True, null=True)),
                ('memberType', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('userUrl', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listId', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('closed', models.BooleanField(default=False)),
                ('pos', models.FloatField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytrello.trelloboard')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=50)),
                ('app_token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardId', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('dueComplete', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('isTemplate', models.BooleanField(default=False)),
                ('pos', models.FloatField()),
                ('shortLink', models.CharField(max_length=10, unique=True)),
                ('shortUrl', models.URLField(unique=True)),
                ('cardUrl', models.URLField(blank=True, null=True)),
                ('dateLastActivity', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytrello.trelloboard')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytrello.trellolist')),
                ('members', models.ManyToManyField(related_name='trello_card_members', to='pytrello.TrelloUser')),
                ('votedMembers', models.ManyToManyField(related_name='trello_card_voted_members', to='pytrello.TrelloUser')),
            ],
        ),
        migrations.AddField(
            model_name='trelloboard',
            name='memberCreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pytrello.trellouser'),
        ),
        migrations.CreateModel(
            name='TrelloAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionId', models.CharField(max_length=32, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('appCreator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trello_action_app_creator', to='pytrello.trellouser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trello_action_member', to='pytrello.trellouser')),
                ('memberCreator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trello_action_member_creator', to='pytrello.trellouser')),
            ],
        ),
    ]
