# Generated by Django 3.2.13 on 2022-06-10 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pytrello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrelloBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytrello.trelloboard')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytrello.trelloconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
