# Generated by Django 3.2.13 on 2022-06-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0002_mytrelloboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloaction',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
