# Generated by Django 3.2.13 on 2022-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0003_alter_trelloaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloboard',
            name='idOrganization',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
