# Generated by Django 3.2.13 on 2022-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0004_alter_trelloboard_idorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trelloboard',
            name='shortLink',
        ),
        migrations.AddField(
            model_name='trelloboard',
            name='fullUrl',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trelloboard',
            name='shortUrl',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
