# Generated by Django 3.2.13 on 2022-09-20 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0006_remove_trelloboard_fullurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellocard',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
