# Generated by Django 3.2.13 on 2022-09-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0007_trellocard_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellocard',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
