# Generated by Django 3.2.13 on 2022-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytrello', '0010_trellouser_m_developer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trelloboard',
            name='m_project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
