# Generated by Django 3.2.13 on 2022-06-20 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('user_id', models.BigIntegerField()),
                ('login', models.CharField(max_length=32)),
                ('admin', models.BooleanField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(blank=True, max_length=32, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_login_on', models.DateTimeField(blank=True, null=True)),
                ('passwd_changed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('domain_url', 'login'), ('domain_url', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RedmineTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('tracker_id', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('domain_url', 'tracker_id')},
            },
        ),
        migrations.CreateModel(
            name='RedmineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('status_id', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('domain_url', 'status_id')},
            },
        ),
        migrations.CreateModel(
            name='RedmineProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('project_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('inherit_members', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('domain_url', 'identifier'), ('domain_url', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='RedminePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('priority_id', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'unique_together': {('domain_url', 'priority_id')},
            },
        ),
        migrations.CreateModel(
            name='RedmineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('api_access_key', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedmineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('issue_id', models.BigIntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redmine_issue_assignee', to='pyredmine.redmineuser')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readmine_issue_author', to='pyredmine.redmineuser')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redminepriority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineproject')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redminestatus')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redminetracker')),
            ],
            options={
                'unique_together': {('domain_url', 'issue_id')},
            },
        ),
    ]
