# Generated by Django 3.2.13 on 2022-06-20 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyredmine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRedmineProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
