# Generated by Django 3.2.13 on 2022-06-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0002_myredmineproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redmineissue',
            name='is_private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmineproject',
            name='inherit_members',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmineproject',
            name='is_public',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RedmineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('file_id', models.BigIntegerField()),
                ('filename', models.FilePathField()),
                ('filesize', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('digest', models.CharField(blank=True, max_length=100, null=True)),
                ('downloads', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineproject')),
            ],
            options={
                'unique_together': {('domain_url', 'file_id')},
            },
        ),
    ]
