# Generated by Django 3.2.13 on 2022-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0003_auto_20220621_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redminefile',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
