# Generated by Django 3.2.13 on 2022-07-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0004_alter_redminefile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmineWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField()),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyredmine.redmineuser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redminewiki')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineproject')),
            ],
            options={
                'unique_together': {('domain_url', 'project', 'title')},
            },
        ),
    ]
