# Generated by Django 3.2.13 on 2022-07-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0005_redminewiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redminewiki',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineproject'),
        ),
    ]
