# Generated by Django 3.2.13 on 2022-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0008_auto_20220925_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmineproject',
            name='m_project_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
