# Generated by Django 3.2.13 on 2022-10-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyredmine', '0010_redmineuser_m_developer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmineissue',
            name='fixed_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyredmine.redmineversion'),
        ),
    ]
