# Generated by Django 3.2.13 on 2022-06-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('email_domain', models.CharField(max_length=100)),
                ('icon', models.URLField()),
                ('avatar_base_url', models.URLField()),
                ('is_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('color', models.CharField(max_length=6)),
                ('tz', models.CharField(max_length=24)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_owner', models.BooleanField(blank=True, null=True)),
                ('is_primary_owner', models.BooleanField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(blank=True, null=True)),
                ('is_ultra_restricted', models.BooleanField(blank=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, null=True)),
                ('is_app_user', models.BooleanField(blank=True, null=True)),
                ('is_email_confirmed', models.BooleanField(blank=True, null=True)),
                ('updated', models.IntegerField(blank=True, null=True)),
                ('who_can_share_contact_card', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('skype', models.CharField(blank=True, max_length=64, null=True)),
                ('display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackteam')),
            ],
        ),
        migrations.CreateModel(
            name='SlackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_normalized', models.CharField(max_length=100)),
                ('is_channel', models.BooleanField(blank=True, null=True)),
                ('is_group', models.BooleanField(blank=True, null=True)),
                ('is_im', models.BooleanField(blank=True, null=True)),
                ('is_mpim', models.BooleanField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('is_archived', models.BooleanField(blank=True, null=True)),
                ('is_general', models.BooleanField(blank=True, null=True)),
                ('is_shared', models.BooleanField(blank=True, null=True)),
                ('is_org_shared', models.BooleanField(blank=True, null=True)),
                ('is_pending_ext_shared', models.BooleanField(blank=True, null=True)),
                ('is_ext_shared', models.BooleanField(blank=True, null=True)),
                ('unlinked', models.IntegerField(blank=True, null=True)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('members', models.ManyToManyField(to='pyslack.SlackUser')),
                ('shared_teams', models.ManyToManyField(to='pyslack.SlackTeam')),
            ],
        ),
    ]
