# Generated by Django 3.2.13 on 2022-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0002_slackhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='history',
            field=models.ManyToManyField(to='pyslack.SlackHistory'),
        ),
    ]
