# Generated by Django 3.2.13 on 2022-06-14 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyslack', '0003_slackchannel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackchannel',
            name='created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MySlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackchannel')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
