# Generated by Django 3.2.13 on 2022-06-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0004_auto_20220614_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackchannel',
            name='history',
        ),
        migrations.AddField(
            model_name='slackhistory',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackchannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackhistory',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_inviter', to='pyslack.slackuser'),
        ),
        migrations.AlterField(
            model_name='slackhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to='pyslack.slackuser'),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='updated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='who_can_share_contact_card',
            field=models.CharField(max_length=32),
        ),
    ]
