# Generated by Django 3.2.13 on 2022-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0005_auto_20220614_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackchannel',
            name='created',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='updated',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
