# Generated by Django 3.2.13 on 2022-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0007_alter_slackconfiguration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackhistory',
            name='subtype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
