# Generated by Django 3.2.13 on 2022-06-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0008_alter_slackhistory_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to='pyslack.slackuser'),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='tz',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
