# Generated by Django 3.2.13 on 2022-06-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0011_alter_slackuser_who_can_share_contact_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackteam',
            name='avatar_base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='email_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
