# Generated by Django 3.2.13 on 2022-09-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0012_auto_20220614_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackconfiguration',
            name='user',
        ),
        migrations.DeleteModel(
            name='MySlackChannel',
        ),
        migrations.DeleteModel(
            name='SlackConfiguration',
        ),
    ]
