# Generated by Django 3.2.13 on 2022-09-12 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0013_auto_20220905_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackhistory',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_parent_user', to='pyslack.slackuser'),
        ),
        migrations.AddField(
            model_name='slackhistory',
            name='thread_ts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
