# Generated by Django 3.2.13 on 2022-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0014_auto_20220912_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackhistory',
            name='num_reactions',
            field=models.IntegerField(default=0),
        ),
    ]
