# Generated by Django 3.2.13 on 2022-09-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0015_slackhistory_num_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackuser')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyslack.slackhistory')),
            ],
        ),
    ]
