# Generated by Django 3.2.13 on 2022-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0016_slackmentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='slackhistory',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='slackmentions',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
