# Generated by Django 3.2.13 on 2022-10-18 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyslack', '0017_auto_20220927_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmentions',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
