# Generated by Django 3.2.13 on 2022-06-17 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pychatwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChatworkRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychatwork.chatworkconfiguration')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychatwork.chatworkroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
