# Generated by Django 3.2.13 on 2022-09-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pychatwork', '0002_mychatworkroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkmessage',
            name='reply_to_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatworkMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychatwork.chatworkmember')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychatwork.chatworkmessage')),
            ],
        ),
    ]
