# Generated by Django 3.2.13 on 2022-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychatwork', '0003_auto_20220913_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkmention',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatworkmessage',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatworkroom',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
