# Generated by Django 3.2.13 on 2022-10-18 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pychatwork', '0004_auto_20220927_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkmention',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatworkroom',
            name='created_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
