# Generated by Django 3.2.13 on 2022-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychatwork', '0006_chatworkmember_m_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatworkmember',
            name='chatwork_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
