# Generated by Django 3.2.13 on 2022-11-13 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureboardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('project_id', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('createTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('domain_url', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='AzureboardSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('sprint_id', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(db_index=True, max_length=100)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyazureboard.azureboardproject')),
            ],
            options={
                'unique_together': {('domain_url', 'sprint_id')},
            },
        ),
        migrations.CreateModel(
            name='AzureboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_developer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=48)),
                ('displayName', models.CharField(max_length=64)),
                ('uniqueName', models.EmailField(max_length=254)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('domain_url', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='AzureboardWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('wi_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=16, null=True)),
                ('createdDate', models.DateTimeField()),
                ('changedDate', models.DateTimeField()),
                ('changedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azureboard_workitem_changer', to='pyazureboard.azureboarduser')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azureboard_workitem_creator', to='pyazureboard.azureboarduser')),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyazureboard.azureboardsprint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyazureboard.azureboardproject')),
            ],
            options={
                'unique_together': {('domain_url', 'wi_id')},
            },
        ),
    ]
