# Generated by Django 3.2.13 on 2022-11-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyazureboard', '0002_azureboardworkitem_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureboardsprint',
            name='finishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azureboardsprint',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
