# Generated by Django 3.2.13 on 2022-11-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyazureboard', '0003_auto_20221114_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureboardWikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('wiki_identifier', models.CharField(db_index=True, max_length=64)),
                ('wiki_path', models.URLField(db_index=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyazureboard.azureboardproject')),
            ],
        ),
    ]
