# Generated by Django 3.2.13 on 2022-11-27 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyazureboard', '0004_azureboardwikipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureboardwikipage',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='azureboardwikipage',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
