# Generated by Django 3.2.13 on 2022-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyazureboard', '0005_auto_20221128_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureboarduser',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
