# Generated by Django 3.2.13 on 2022-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0002_auto_20220528_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='commitComments',
            field=models.ManyToManyField(to='pygithub.GithubCommitComment'),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='commits',
            field=models.ManyToManyField(to='pygithub.GithubCommit'),
        ),
    ]
