# Generated by Django 3.2.13 on 2022-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0003_auto_20220529_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepository',
            old_name='commitComments',
            new_name='commit_comments',
        ),
        migrations.RemoveField(
            model_name='githubcommit',
            name='verification_payload',
        ),
        migrations.RemoveField(
            model_name='githubcommit',
            name='verification_reason',
        ),
        migrations.RemoveField(
            model_name='githubcommit',
            name='verification_signature',
        ),
        migrations.RemoveField(
            model_name='githubcommit',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='githubcommitcomment',
            name='commit',
        ),
        migrations.AddField(
            model_name='githubcommitcomment',
            name='commit_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
