# Generated by Django 3.2.13 on 2022-05-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0004_auto_20220529_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='repo_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='updated_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_owner', to='pygithub.githubuser'),
        ),
    ]
