# Generated by Django 3.2.13 on 2022-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0005_auto_20220529_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
