# Generated by Django 3.2.13 on 2022-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0007_alter_githubuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfiguration',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
