# Generated by Django 3.2.13 on 2022-06-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pygithub', '0008_githubconfiguration_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygithub.githubconfiguration')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygithub.githubrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
