# Generated by Django 3.2.13 on 2022-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0011_githubpullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='pull_requests',
            field=models.ManyToManyField(to='pygithub.GithubPullRequest'),
        ),
    ]
