# Generated by Django 3.2.13 on 2022-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0012_githubrepository_pull_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
