# Generated by Django 3.2.13 on 2022-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygithub', '0013_auto_20220919_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubpullrequest',
            name='requested_reviewers',
            field=models.ManyToManyField(related_name='github_pr_reviewers', to='pygithub.GithubUser'),
        ),
    ]
