# Generated by Django 3.2.13 on 2022-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0003_auto_20220529_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabcommit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gitlabcommit',
            name='committer',
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='author_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='authored_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='committed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='committer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gitlabcommit',
            name='committer_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
