# Generated by Django 3.2.13 on 2022-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0004_auto_20220529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabcommit',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabcommit',
            name='committer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
