# Generated by Django 3.2.13 on 2022-06-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pygitlab', '0005_auto_20220529_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGitlabGroupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False)),
                ('is_project', models.BooleanField(default=False)),
                ('configuartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygitlab.gitlabconfiguration')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pygitlab.gitlabgroup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pygitlab.gitlabproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
