# Generated by Django 3.2.13 on 2022-06-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0006_mygitlabgroupproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygitlabgroupproject',
            old_name='configuartion',
            new_name='configuration',
        ),
    ]
