# Generated by Django 3.2.13 on 2022-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0007_rename_configuartion_mygitlabgroupproject_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_id', models.CharField(db_index=True, max_length=100)),
                ('format', models.CharField(max_length=24)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('encoding', models.CharField(max_length=16)),
                ('group_or_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='gitlabcommit',
            name='commit_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gitlabgroup',
            name='group_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gitlabuser',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
