# Generated by Django 3.2.13 on 2022-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0008_auto_20220717_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabgroup',
            name='wikis',
            field=models.ManyToManyField(to='pygitlab.GitlabWiki'),
        ),
        migrations.AddField(
            model_name='gitlabproject',
            name='wikis',
            field=models.ManyToManyField(to='pygitlab.GitlabWiki'),
        ),
    ]
