# Generated by Django 3.2.13 on 2022-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0010_auto_20220804_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='work_in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gitlabproject',
            name='merge_requests',
            field=models.ManyToManyField(to='pygitlab.GitlabMergeRequest'),
        ),
    ]
