# Generated by Django 3.2.13 on 2022-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0011_auto_20220804_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', to='pygitlab.GitlabUser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to='pygitlab.GitlabUser'),
        ),
    ]
