# Generated by Django 3.2.13 on 2022-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0015_gitlabwiki_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabwiki',
            name='m_project_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
