# Generated by Django 3.2.13 on 2022-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0016_gitlabwiki_m_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='m_project_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
