# Generated by Django 3.2.13 on 2022-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygitlab', '0018_gitlabuser_m_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to='pygitlab.GitlabUser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='pygitlab.GitlabUser'),
        ),
    ]
