# Generated by Django 3.2.13 on 2022-10-30 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('projectId', models.BigIntegerField(db_index=True)),
                ('projectKey', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('archived', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('domain_url', 'projectId')},
            },
        ),
        migrations.CreateModel(
            name='BacklogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_developer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('backlogId', models.BigIntegerField(db_index=True)),
                ('userId', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('roleType', models.PositiveSmallIntegerField()),
                ('lang', models.CharField(max_length=4)),
                ('mailAddress', models.EmailField(db_index=True, max_length=254)),
                ('nulabId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('domain_url', 'backlogId')},
            },
        ),
        migrations.CreateModel(
            name='BacklogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('versionId', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('releaseDueDate', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybacklog.backlogproject')),
            ],
            options={
                'unique_together': {('domain_url', 'versionId')},
            },
        ),
        migrations.CreateModel(
            name='BacklogWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('wikiId', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('createdUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_wiki_created_user', to='pybacklog.backloguser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybacklog.backlogproject')),
                ('updatedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_wiki_updated_user', to='pybacklog.backloguser')),
            ],
            options={
                'unique_together': {('domain_url', 'wikiId')},
            },
        ),
        migrations.CreateModel(
            name='BacklogIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('issueId', models.BigIntegerField(db_index=True)),
                ('issueKey', models.CharField(db_index=True, max_length=64)),
                ('keyId', models.BigIntegerField(db_index=True)),
                ('issueType', models.CharField(db_index=True, max_length=16)),
                ('summary', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(db_index=True, max_length=16)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('estimatedHours', models.IntegerField(blank=True, null=True)),
                ('actualHours', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_issue_assignee', to='pybacklog.backloguser')),
                ('createdUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_issue_created_user', to='pybacklog.backloguser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybacklog.backlogproject')),
                ('updatedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_issue_updated_user', to='pybacklog.backloguser')),
                ('versions', models.ManyToManyField(blank=True, null=True, related_name='backlog_versions', to='pybacklog.BacklogVersion')),
            ],
            options={
                'unique_together': {('domain_url', 'issueId')},
            },
        ),
    ]
