# Generated by Django 3.2.13 on 2022-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backloguser',
            name='user_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
