# Generated by Django 3.2.13 on 2022-06-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='comments',
            field=models.ManyToManyField(to='pyjira.JiraIssueComment'),
        ),
    ]
