# Generated by Django 3.2.13 on 2022-06-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyjira', '0002_jiraissue_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyjira.jiraconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyjira.jiraproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
