# Generated by Django 3.2.13 on 2022-06-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0003_myjiraproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraissue',
            name='isWatching',
        ),
        migrations.RemoveField(
            model_name='jirauser',
            name='accountType',
        ),
        migrations.AddField(
            model_name='jirapriority',
            name='iconUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraproject',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyjira.jirauser'),
        ),
        migrations.AddField(
            model_name='jiraproject',
            name='self',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jirauser',
            name='locale',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jirauser',
            name='timeZone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
