# Generated by Django 3.2.13 on 2022-06-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0004_auto_20220605_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiraissue',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jiraissuecomment',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jiraissuetype',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jirapriority',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jiraproject',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jirastatus',
            old_name='self',
            new_name='self_url',
        ),
        migrations.RenameField(
            model_name='jirauser',
            old_name='self',
            new_name='self_url',
        ),
    ]
