# Generated by Django 3.2.13 on 2022-06-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0005_auto_20220605_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myjiraproject',
            old_name='configuartion',
            new_name='configuration',
        ),
    ]
