# Generated by Django 3.2.13 on 2022-07-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0006_rename_configuartion_myjiraproject_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('self_url', models.URLField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyjira.jiraproject')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_id', models.IntegerField()),
                ('self_url', models.URLField(blank=True, null=True, unique=True)),
                ('state', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('goal', models.CharField(blank=True, max_length=64, null=True)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyjira.jiraboard')),
            ],
        ),
    ]
