# Generated by Django 3.2.13 on 2022-07-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0007_jiraboard_jirasprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jirasprint',
            old_name='boardId',
            new_name='board',
        ),
    ]
