# Generated by Django 3.2.13 on 2022-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0008_rename_boardid_jirasprint_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirasprint',
            name='issues',
            field=models.ManyToManyField(to='pyjira.JiraIssue'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='uuid',
            field=models.CharField(db_index=True, max_length=48),
        ),
    ]
