# Generated by Django 3.2.13 on 2022-09-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0009_auto_20220823_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjiraproject',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='myjiraproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='myjiraproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='JiraConfiguration',
        ),
        migrations.DeleteModel(
            name='MyJiraProject',
        ),
    ]
