# Generated by Django 3.2.13 on 2022-09-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0010_auto_20220905_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraproject',
            name='issues',
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyjira.jiraproject'),
        ),
    ]
