# Generated by Django 3.2.13 on 2022-09-11 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0011_auto_20220905_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirasprint',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
