# Generated by Django 3.2.13 on 2022-09-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0012_jirasprint_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirasprint',
            name='create_date',
        ),
    ]
