# Generated by Django 3.2.13 on 2022-10-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0013_remove_jirasprint_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraproject',
            name='m_project_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
