# Generated by Django 3.2.13 on 2022-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0015_jirasprint_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirasprint',
            name='issues',
            field=models.ManyToManyField(related_name='jira_sprints', to='pyjira.JiraIssue'),
        ),
    ]
