# Generated by Django 3.2.13 on 2022-10-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyjira', '0016_alter_jirasprint_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirauser',
            name='m_developer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
