# Generated by Django 3.2.13 on 2022-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0002_ddocumentdevelopersprint_ddomaindeveloper_ddomainmaster_dskilldeveloper_dskillmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
