# Generated by Django 3.2.13 on 2022-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0004_dproject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dproject',
            name='avg_lead_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='avg_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='avg_work_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='current_sprint_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='num_of_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='progress_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='remain_work_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='sprint_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='total_num_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
