# Generated by Django 3.2.13 on 2022-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0005_auto_20220710_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dteam',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dteam',
            name='num_of_documents',
        ),
        migrations.AddField(
            model_name='dteam',
            name='num_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dteam',
            name='num_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dteam',
            name='avg_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dteam',
            name='avg_work_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
