# Generated by Django 3.2.13 on 2022-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0006_auto_20220710_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsprint',
            name='work_hour_persion',
        ),
        migrations.AddField(
            model_name='dsprint',
            name='num_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='source',
            field=models.CharField(blank=True, choices=[('github', 'GITHUB'), ('gitlab', 'GITLAB'), ('slack', 'SLACK'), ('chatwork', 'CHATWORK'), ('jira', 'JIRA'), ('trello', 'TRELLO'), ('redmine', 'REDMINE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='avg_work_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='close_work_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='num_message',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='num_new_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='num_prs_merged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='num_pull_request',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='num_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='total_work_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsprint',
            name='velocity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
