# Generated by Django 3.2.13 on 2022-07-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0007_auto_20220710_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddeveloper',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dcompany'),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='avg_lead_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='avg_review_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='avg_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='avg_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='avg_work_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='developer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='num_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='avg_lead_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_messages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_new_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_prs_merged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_pull_requests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='num_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='review_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
