# Generated by Django 3.2.13 on 2022-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0008_auto_20220710_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='dproject',
            name='project_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
