# Generated by Django 3.2.13 on 2022-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0009_dproject_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddeveloperteammap',
            old_name='tool',
            new_name='team',
        ),
        migrations.AddField(
            model_name='dproject',
            name='num_backlog',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
