# Generated by Django 3.2.13 on 2022-08-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreauth', '0002_auto_20220821_1524'),
        ('dbanalysis', '0010_auto_20220710_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=64)),
                ('batch_type', models.PositiveSmallIntegerField(choices=[(1, 'error'), (2, 'warning'), (3, 'info')])),
                ('content', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreauth.dcompany')),
            ],
        ),
        migrations.CreateModel(
            name='DCareerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DCareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DDeveloperCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_month', models.DateField()),
                ('end_month', models.DateField()),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'coder'), (2, 'manager'), (3, 'team leader')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDeveloperMentionFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DDeveloperMentionTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DDeveloperProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.FloatField()),
                ('total_expected_work_hours', models.FloatField()),
                ('work_rate', models.FloatField()),
                ('num_documents', models.IntegerField(default=0)),
                ('num_messages', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('num_mentions', models.IntegerField(default=0)),
                ('avg_lead_time', models.FloatField()),
                ('num_new_ticket', models.IntegerField(default=0)),
                ('num_pull_requests', models.IntegerField(default=0)),
                ('num_prs_merged', models.IntegerField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('review_hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DProjectDeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DProjectDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DProjectToolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='DDeveloperTool',
            new_name='DDeveloperToolMap',
        ),
        migrations.RemoveField(
            model_name='dgroup',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='dpullrequest',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='dpullrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='dpullrequest',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='dticket',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='dticket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='dticket',
            name='sprint',
        ),
        migrations.RenameField(
            model_name='ddocumentdevelopersprint',
            old_name='num_documents',
            new_name='num_document',
        ),
        migrations.RenameField(
            model_name='dsprint',
            old_name='num_message',
            new_name='num_comments',
        ),
        migrations.RenameField(
            model_name='dsprint',
            old_name='num_new_tickets',
            new_name='num_documents',
        ),
        migrations.RemoveField(
            model_name='ddeveloper',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dproject',
            name='progress_rate',
        ),
        migrations.RemoveField(
            model_name='dsprint',
            name='source',
        ),
        migrations.AddField(
            model_name='ddeveloperprojectsprint',
            name='num_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ddeveloperprojectsprint',
            name='num_mentions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ddeveloperprojectsprint',
            name='num_reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ddomainmaster',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dproject',
            name='backlog_sprint_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dproject',
            name='num_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dproject',
            name='num_mentions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dproject',
            name='num_messages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dproject',
            name='num_reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dproject',
            name='project_phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Operated'), (2, 'Modified'), (3, 'New')], default=3),
        ),
        migrations.AddField(
            model_name='dproject',
            name='project_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dskillmaster',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='num_mentions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='num_messages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='num_new_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsprint',
            name='num_reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dteam',
            name='avg_lead_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloper',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreauth.dcompany'),
        ),
        migrations.AlterField(
            model_name='ddomainmaster',
            name='domain_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreauth.dcompany'),
        ),
        migrations.DeleteModel(
            name='DCompany',
        ),
        migrations.DeleteModel(
            name='DGroup',
        ),
        migrations.DeleteModel(
            name='DPullRequest',
        ),
        migrations.DeleteModel(
            name='DTicket',
        ),
        migrations.AddField(
            model_name='dprojecttoolinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='dprojecttoolinfo',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dtoolmaster'),
        ),
        migrations.AddField(
            model_name='dprojectdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddomainmaster'),
        ),
        migrations.AddField(
            model_name='dprojectdomain',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='dprojectdeveloperskill',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='dprojectdeveloperskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='dprojectdeveloperskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dskillmaster'),
        ),
        migrations.AddField(
            model_name='ddeveloperproject',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddeveloperproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionto',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_to_developer', to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionto',
            name='mention_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_to_developer', to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionfrom',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_from_developer', to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionfrom',
            name='mention_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_from_developer', to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddevelopermentionfrom',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='ddevelopercareer',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddeveloper'),
        ),
        migrations.AddField(
            model_name='ddevelopercareer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
        migrations.AddField(
            model_name='dcareerskill',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopercareer'),
        ),
        migrations.AddField(
            model_name='dcareerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dskillmaster'),
        ),
        migrations.AddField(
            model_name='dcareerdomain',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopercareer'),
        ),
        migrations.AddField(
            model_name='dcareerdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddomainmaster'),
        ),
        migrations.AddField(
            model_name='dbatchlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dproject'),
        ),
    ]
