# Generated by Django 3.2.13 on 2022-08-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0011_auto_20220821_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dproject',
            name='source',
        ),
    ]
