# Generated by Django 3.2.13 on 2022-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0013_auto_20220822_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddeveloperproject',
            name='avg_lead_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ddeveloperproject',
            name='review_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ddeveloperproject',
            name='total_expected_work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperproject',
            name='velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddeveloperproject',
            name='work_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
