# Generated by Django 3.2.13 on 2022-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0014_auto_20220822_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='total_expected_work_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ddeveloperprojectsprint',
            name='velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dprojecttoolinfo',
            name='payload',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dprojecttoolinfo',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dprojecttoolinfo',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
