# Generated by Django 3.2.13 on 2022-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0016_auto_20220901_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprojecttoolinfo',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
