# Generated by Django 3.2.13 on 2022-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0018_alter_dprojecttoolinfo_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddevelopertoolmap',
            name='tool_id',
            field=models.IntegerField(choices=[(1, 'jira'), (2, 'slack'), (3, 'chatwork'), (4, 'github'), (5, 'gitlab'), (6, 'trello'), (7, 'redmine')]),
        ),
    ]
