# Generated by Django 3.2.13 on 2022-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0019_alter_ddevelopertoolmap_tool_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprojecttoolinfo',
            name='m_tool_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
