# Generated by Django 3.2.13 on 2022-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0023_auto_20221114_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddevelopertoolmap',
            name='s3_bucket_key',
            field=models.URLField(blank=True, null=True),
        ),
    ]
