# Generated by Django 3.2.13 on 2023-01-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0024_ddevelopertoolmap_s3_bucket_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.BigIntegerField()),
                ('tool_name', models.CharField(max_length=64)),
            ],
        ),
    ]
