# Generated by Django 3.2.13 on 2023-01-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0025_dtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtool',
            name='tool_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
