# Generated by Django 3.2.13 on 2023-01-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0026_alter_dtool_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprojecttoolinfo',
            name='d_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbanalysis.dtool'),
        ),
    ]
