# Generated by Django 3.2.13 on 2023-01-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0027_dprojecttoolinfo_d_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dprojecttoolinfo',
            name='m_tool_id',
        ),
    ]
