# Generated by Django 3.2.13 on 2023-02-05 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0028_remove_dprojecttoolinfo_m_tool_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DChannel',
            fields=[
                ('channel_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('channel_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dtool')),
            ],
        ),
        migrations.CreateModel(
            name='DMessage',
            fields=[
                ('message_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('reply_to_id', models.BigIntegerField(blank=True, null=True)),
                ('contents', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dchannel')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopertoolmap')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DMention',
            fields=[
                ('mention_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mention_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopertoolmap')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
            ],
        ),
    ]
