# Generated by Django 3.2.13 on 2023-02-19 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0030_dmessage_tool_message_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPullRequest',
            fields=[
                ('pull_request_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('merge_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopertoolmap')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
            ],
        ),
    ]
