# Generated by Django 3.2.13 on 2023-02-26 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0031_dpullrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSprint',
            fields=[
                ('sprint_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='_', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DTicket',
            fields=[
                ('ticket_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('difficulty', models.CharField(default='_', max_length=16)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopertoolmap')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dsprint')),
            ],
        ),
    ]
