# Generated by Django 3.2.13 on 2023-02-27 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0032_dsprint_dticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDocument',
            fields=[
                ('document_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.ddevelopertoolmap')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dprojecttoolinfo')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbanalysis.dsprint')),
            ],
        ),
    ]
