# Generated by Django 3.2.13 on 2023-02-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0033_ddocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ddocument',
            unique_together={('project', 'title')},
        ),
    ]
