# Generated by Django 3.2.13 on 2023-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbanalysis', '0034_alter_ddocument_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsprint',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dticket',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dsprint',
            unique_together={('project', 'unique_id')},
        ),
        migrations.AlterUniqueTogether(
            name='dticket',
            unique_together={('project', 'unique_id')},
        ),
    ]
