# Generated by Django 3.2.13 on 2022-11-04 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_developer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('accountId', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('publicName', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('domain_url', 'accountId')},
            },
        ),
        migrations.CreateModel(
            name='ConfluenceSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('domain_url', models.URLField(db_index=True)),
                ('spaceId', models.BigIntegerField(db_index=True)),
                ('spaceKey', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyconfluence.confluenceuser')),
            ],
            options={
                'unique_together': {('domain_url', 'spaceId')},
            },
        ),
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(db_index=True)),
                ('pageId', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField()),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('createdUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confluence_page_created_user', to='pyconfluence.confluenceuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyconfluence.confluencespace')),
                ('updatedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confluence_page_updated_user', to='pyconfluence.confluenceuser')),
            ],
            options={
                'unique_together': {('domain_url', 'pageId')},
            },
        ),
    ]
