# Generated by Django 3.2.13 on 2022-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconfluence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluenceuser',
            name='profilePicture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
